# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9babe7ac606f177692a7e5d04624b3ee30bc05bf72d28e012160ce9c68020fba674a1eb21f70a6c89955307507a5675155ceab9da3dffca54bf924ec15a5231a

test:
  secret_key_base: 0c63d3966c31d441d48af2491420e26cfc23192ecd68e04a26be0f7f5aeeaa0c3546b003c1daa4b3f609a1c79038efd3e23879334f6ba09499f06e5bb9f722d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
